'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm3
    
    '''<summary>
    '''pomocniU1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCalculate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnInput As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''temporarP0a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents temporarP0a As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label25 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''k2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents k2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''k3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents k3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''k4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents k4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''k7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents k7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''k6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents k6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label24 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''k1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents k1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''s1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents s1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''u1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents u1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''k5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents k5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pomocniU3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TboxKfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TboxKfc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''OptimumU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OptimumU As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelMaxB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMaxB As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label26 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''mKmaxBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mKmaxBank As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelMaxB0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMaxB0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label27 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MaxIputedB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaxIputedB As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempRedBr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempRedBr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempSumU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempSumU As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempStepU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempStepU As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempSumaOptiU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempSumaOptiU As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempStpCntr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempStpCntr As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempForProbaj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempForProbaj As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempForProbaj0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempForProbaj0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label28 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SumInvest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SumInvest As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label29 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SumOpti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SumOpti As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tempForProbaj1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempForProbaj1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''temporStop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents temporStop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempForProbaj2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempForProbaj2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ImageButtonUK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonUK As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ImageButtonHR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButtonHR As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''TextBoxHelpUK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxHelpUK As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBoxHelpHR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxHelpHR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tempForProbaj3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempForProbaj3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''temporP2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents temporP2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''temporTempP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents temporTempP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''temporarP0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents temporarP0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pomocniU16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pomocniU16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempTextInputU16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempTextInputU16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempK16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempK16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempS16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempS16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempU16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempU16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''temporarP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents temporarP1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tempOpet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tempOpet As Global.System.Web.UI.WebControls.Label
End Class
