'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HrcRc

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Place28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place61 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place62 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place63 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place64 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place37 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1and2lace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1and2lace1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place32 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1and2or2and1lace01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1and2or2and1lace01 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place38 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place36 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1and2lace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1and2lace3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place34 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1and2or2and1lace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1and2or2and1lace3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place39 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place35 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1and2lace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1and2lace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place33 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1and2or2and1lace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1and2or2and1lace2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place40 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place41 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place42 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place43 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place44 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place45 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''P01lace9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P01lace9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2lace9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2lace9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3lace9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3lace9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2or3or4lace9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2or3or4lace9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''P1OR2OR3or4or5lace9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1OR2OR3or4or5lace9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place46 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Labelconsolidate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelconsolidate1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelconsolidate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelconsolidate2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Labelconsolidate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Labelconsolidate3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place47 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place48 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place49 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place52 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place51 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place53 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place54 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place55 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place56 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place57 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place58 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place58 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc21 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Place59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place59 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kfc22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kfc22 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
End Class
